/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.Playlists;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controllers.Usuarios;

/**
 *
 * @author fatec-dsm2
 */
public class FPlaylist extends javax.swing.JFrame {

    /**
     * Creates new form FPlaylist
     */
    public FPlaylist() {
        initComponents();
        refreshar();
    }
    
    public String user;
    
    Playlists play = new Playlists();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_fundo = new javax.swing.JLabel();
        btn_sair = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_editarnome = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JLabel();
        btn_inserirmusic = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_playlist = new javax.swing.JTable();
        img_add = new javax.swing.JLabel();
        btn_visualizar = new javax.swing.JLabel();
        btn_criarplaylist = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        img_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/menu/nav_menu.png"))); // NOI18N

        btn_sair.setOpaque(false);
        btn_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_sairLayout = new javax.swing.GroupLayout(btn_sair);
        btn_sair.setLayout(btn_sairLayout);
        btn_sairLayout.setHorizontalGroup(
            btn_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        btn_sairLayout.setVerticalGroup(
            btn_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        btn_editarnome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/playlists/btn_editarnome.png"))); // NOI18N
        btn_editarnome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editarnomeMouseClicked(evt);
            }
        });

        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/cadusu/btn_voltar.png"))); // NOI18N
        btn_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_voltarMouseClicked(evt);
            }
        });

        btn_inserirmusic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/playlists/btn_inserirmusicas.png"))); // NOI18N
        btn_inserirmusic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_inserirmusicMouseClicked(evt);
            }
        });

        tbl_playlist.setForeground(new java.awt.Color(12, 69, 72));
        tbl_playlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome Playlist", "Quantidade de Músicas", "Minutos", "Data"
            }
        ));
        tbl_playlist.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_playlist.setRowHeight(30);
        tbl_playlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_playlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_playlist);

        img_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/playlists/img_add.png"))); // NOI18N

        btn_visualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/playlists/btn_visualizar.png"))); // NOI18N
        btn_visualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_visualizarMouseClicked(evt);
            }
        });

        btn_criarplaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/playlists/btn_criarplaylist.png"))); // NOI18N
        btn_criarplaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_criarplaylistMouseClicked(evt);
            }
        });

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_voltar)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_editarnome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_inserirmusic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(img_add)
                        .addGap(175, 175, 175))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_visualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(btn_criarplaylist)
                    .addContainerGap(834, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btn_visualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(img_add)
                        .addGap(374, 374, 374))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_inserirmusic)
                            .addComponent(btn_editarnome))
                        .addGap(436, 436, 436))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(btn_criarplaylist)
                    .addContainerGap(870, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(964, Short.MAX_VALUE)
                    .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(185, 185, 185)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(img_fundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1068, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1024, 796));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sairMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_sairMouseClicked

    private void btn_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_voltarMouseClicked
        // TODO add your handling code here:
        FMenu menu = new FMenu();
        menu.lbl_nome.setText(user);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_voltarMouseClicked

    private void btn_criarplaylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_criarplaylistMouseClicked
        // TODO add your handling code here:
        new FMCriarPlaylist().setVisible(true);
    }//GEN-LAST:event_btn_criarplaylistMouseClicked

    private void btn_editarnomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarnomeMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tbl_playlist.getModel();
       // modelo.setNumRows(0);

        int linhaSelecionada = tbl_playlist.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma Playlist para Editar.");
            refreshar();
            return;
        } else {
        // Obtendo o ID da playlist selecionada a partir da tabela
        int idPlaylist = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
        
        
      FMEditarPlaylist FEdit = new FMEditarPlaylist();
    
     //    Passando o ID da playlist para a próxima janela
        FEdit.setIdPlaylist(idPlaylist);
        
        FEdit.txt_editarplaylist.setText(modelo.getValueAt(linhaSelecionada, 1).toString());
        
        FEdit.setVisible(true);
        }
    }//GEN-LAST:event_btn_editarnomeMouseClicked

    private void btn_inserirmusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inserirmusicMouseClicked
        // TODO add your handling code here:

        DefaultTableModel modelo = (DefaultTableModel) tbl_playlist.getModel();
       // modelo.setNumRows(0);

        int linhaSelecionada = tbl_playlist.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma Playlist para Inserir Músicas.");
            refreshar();
            return;
        } else {
        // Obtendo o ID da playlist selecionada a partir da tabela
        int idPlaylist = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
        
        FInserirMusic Finsert = new FInserirMusic();
    
        //Passando o ID da playlist para a próxima janela
        Finsert.user = user;
        Finsert.setIdPlaylist(idPlaylist);
        Finsert.lbl_playlist.setText(modelo.getValueAt(linhaSelecionada, 1).toString());
        
        Finsert.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btn_inserirmusicMouseClicked

    private void btn_visualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visualizarMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tbl_playlist.getModel();
       // modelo.setNumRows(0);

        int linhaSelecionada = tbl_playlist.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma Playlist para visualizar.");
            refreshar();
            return;
        } else {
        // Obtendo o ID da playlist selecionada a partir da tabela
        int idPlaylist = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
        
        
      FVisualizarMusicas FVisu = new FVisualizarMusicas();
    
     //    Passando o ID da playlist para a próxima janela
        FVisu.user = user;
        FVisu.setIdPlaylist(idPlaylist);
        FVisu.lbl_nomePlaylist.setText(modelo.getValueAt(linhaSelecionada, 1).toString());
    
        FVisu.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btn_visualizarMouseClicked

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        refreshar();
        
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void tbl_playlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_playlistMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbl_playlistMouseClicked

    public void refreshar(){
        ResultSet tabela;
        tabela = null;
        
        tabela = play.listarplaylist();
        DefaultTableModel modelo = (DefaultTableModel) tbl_playlist.getModel();
        modelo.setNumRows(0);
        
        try{
            do{
                modelo.addRow(new String[]{tabela.getString(1), tabela.getString(2), tabela.getString(3), tabela.getString(4), tabela.getString(5)});
            }while(tabela.next());
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Erro ao preencher tabela "+erro);
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPlaylist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_criarplaylist;
    private javax.swing.JLabel btn_editarnome;
    private javax.swing.JLabel btn_inserirmusic;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JPanel btn_sair;
    private javax.swing.JLabel btn_visualizar;
    private javax.swing.JLabel btn_voltar;
    private javax.swing.JLabel img_add;
    private javax.swing.JLabel img_fundo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_playlist;
    // End of variables declaration//GEN-END:variables
}
